---
".zdir/20-fzf-git.sh":
  type: file
  url: "https://raw.githubusercontent.com/junegunn/fzf-git.sh/main/fzf-git.sh"

{{ if .is_private -}}
".local/bin/git-credential-pass":
  type: file
  url: "https://raw.githubusercontent.com/cassava/git-credential-pass/main/git-credential-pass"
  executable: true
{{ end -}}

{{ if not .is_headless -}}
".local/share/wezterm/plugins/httpssCssZssZsgithubsDscomsZsmichaelbrusegardsZstablinesDswez":
  type: "git-repo"
  url: "https://github.com/michaelbrusegard/tabline.wez"
  refreshPeriod: "168h"
{{ end -}}
