---
".zdir/20-fzf-git.sh":
  type: file
  url: "https://raw.githubusercontent.com/junegunn/fzf-git.sh/main/fzf-git.sh"

{{ if .is_private -}}
".local/bin/git-credential-pass":
  type: file
  url: "https://raw.githubusercontent.com/cassava/git-credential-pass/main/git-credential-pass"
  executable: true
{{ end -}}
